### PR TITLE
adding analysis to OTA_HotelDescriptiveContentNotifRQ

### PR DESCRIPTION
**Pull request by AgataJakubowska**

### CODE REVIEW

**Review by bluejurand — COMMENTED** [review]
Cell 24: `HotelDescriptiveContent_HotelName by HotelDescriptiveContent_HotelCode`
Encoding of one hotel name on x label is not working correctly.
The same for cells: 82 `Checking against null values for GuestRoom_RoomTypeName`, 116 `Checking against null values for TypeRoom_Size`
Zrzut ekranu z 2022-01-05 10-22-20

**Comment by AgataJakubowska** [comment]
> Cell 24: `HotelDescriptiveContent_HotelName by HotelDescriptiveContent_HotelCode` Encoding of one hotel name on x label is not working correctly. The same for cells: 82 `Checking against null values for GuestRoom_RoomTypeName`, 116 `Checking against null values for TypeRoom_Size` Zrzut ekranu z 2022-01-05 10-22-20

@bluejurand yes, I know, I tried everything but did not work. Maybe you have any proposition because changing font for with non-latin glyphs doesn't help much

**Comment by bluejurand** [comment]
What is the purpose of this plots with phone numbers for hotels?
Zrzut ekranu z 2022-01-05 11-19-32

**Comment by robsztal** [comment]
Same like [here](https://github.com/Bidroombv/eda/pull/8#issuecomment-1005550130)

**Comment by bluejurand** [comment]
> > Cell 24: `HotelDescriptiveContent_HotelName by HotelDescriptiveContent_HotelCode` Encoding of one hotel name on x label is not working correctly. The same for cells: 82 `Checking against null values for GuestRoom_RoomTypeName`, 116 `Checking against null values for TypeRoom_Size` Zrzut ekranu z 2022-01-05 10-22-20
> 
> @bluejurand yes, I know, I tried everything but did not work. Maybe you have any proposition because changing font for with non-latin glyphs doesn't help much

Have You checked those options https://stackoverflow.com/a/10960464/9076574 ?

**Comment by AgataJakubowska** [comment]
> What is the purpose of this plots with phone numbers for hotels? Zrzut ekranu z 2022-01-05 11-19-32

@bluejurand you are right, it was useless. I removed it

**Comment by AgataJakubowska** [comment]
> > > Cell 24: `HotelDescriptiveContent_HotelName by HotelDescriptiveContent_HotelCode` Encoding of one hotel name on x label is not working correctly. The same for cells: 82 `Checking against null values for GuestRoom_RoomTypeName`, 116 `Checking against null values for TypeRoom_Size` Zrzut ekranu z 2022-01-05 10-22-20
> > 
> > 
> > @bluejurand yes, I know, I tried everything but did not work. Maybe you have any proposition because changing font for with non-latin glyphs doesn't help much
> 
> Have You checked those options https://stackoverflow.com/a/10960464/9076574 ?

@bluejurand as I wrote before changing font does not help. To visualize it I used proposition from that stackoverflow suggestion on the first chart, please see

**Comment by bluejurand** [comment]
> > > > Cell 24: `HotelDescriptiveContent_HotelName by HotelDescriptiveContent_HotelCode` Encoding of one hotel name on x label is not working correctly. The same for cells: 82 `Checking against null values for GuestRoom_RoomTypeName`, 116 `Checking against null values for TypeRoom_Size` Zrzut ekranu z 2022-01-05 10-22-20
> > > 
> > > 
> > > @bluejurand yes, I know, I tried everything but did not work. Maybe you have any proposition because changing font for with non-latin glyphs doesn't help much
> > 
> > 
> > Have You checked those options https://stackoverflow.com/a/10960464/9076574 ?
> 
> @bluejurand as I wrote before changing font does not help. To visualize it I used proposition from that stackoverflow suggestion on the first chart, please see

As I have checked all of that three cases are caused by Chinese names like hotel name `深圳伊敦雅诗阁服务公寓` - `Shenzhen Eden Ascott Service Apartment`. So the solution is simply to translate them from Chinese to English.

**Comment by AgataJakubowska** [comment]
> Same like [here](https://github.com/Bidroombv/eda/pull/8#issuecomment-1005550130)

@robsztal please see the answer [here ](https://github.com/Bidroombv/eda/pull/8#issuecomment-1005576752)

**Comment by AgataJakubowska** [comment]
> > > > > Cell 24: `HotelDescriptiveContent_HotelName by HotelDescriptiveContent_HotelCode` Encoding of one hotel name on x label is not working correctly. The same for cells: 82 `Checking against null values for GuestRoom_RoomTypeName`, 116 `Checking against null values for TypeRoom_Size` Zrzut ekranu z 2022-01-05 10-22-20
> > > > 
> > > > 
> > > > @bluejurand yes, I know, I tried everything but did not work. Maybe you have any proposition because changing font for with non-latin glyphs doesn't help much
> > > 
> > > 
> > > Have You checked those options https://stackoverflow.com/a/10960464/9076574 ?
> > 
> > 
> > @bluejurand as I wrote before changing font does not help. To visualize it I used proposition from that stackoverflow suggestion on the first chart, please see
> 
> As I have checked all of that three cases are caused by Chinese names like hotel name `深圳伊敦雅诗阁服务公寓` - `Shenzhen Eden Ascott Service Apartment`. So the solution is simply to translate them from Chinese to English.

@bluejurand thank you! you are right, the simplest solution is the best. I already translated.

**Review by bluejurand — APPROVED** [review]

**Review by robsztal — APPROVED** [review]

**Pull request merged**
