### PR TITLE
analysis for type of messages OTA_HotelInvCountNotifRQ

### PR DESCRIPTION
**Pull request by AgataJakubowska**

### CODE REVIEW

**Review by robsztal — APPROVED** [review]
I think that these 2 last graphs shows some trend over time so maybe using a line chart would show it better?

**Comment by AgataJakubowska** [comment]
> I think that these 2 last graphs shows some trend over time so maybe using a line chart would show it better?

@robsztal thank you for the tip, I have added analysis

**Comment by bluejurand** [comment]
Cell 26: Checking against null values Start
Can you sort / rank these dates?
The same for cell 28 Checking against null values for End

**Review by bluejurand — COMMENTED** [review]
Cell 41: Strat over Time
Can You change the size of those x & y labels & legend
The same for cell 42 End over Time

**Comment by AgataJakubowska** [comment]
> Cell 41: Strat over Time Can You change the size of those x & y labels & legend The same for cell 42 End over Time

@bluejurand sorted!

**Comment by AgataJakubowska** [comment]
> Cell 26: Checking against null values Start Can you sort / rank these dates? The same for cell 28 Checking against null values for End

@bluejurand  sorted

**Comment by bluejurand** [comment]
> > Cell 41: Strat over Time Can You change the size of those x & y labels & legend The same for cell 42 End over Time
> 
> @bluejurand sorted!

I still see them in the same small sizes
Zrzut ekranu z 2022-01-05 11-37-28

**Comment by AgataJakubowska** [comment]
> > > Cell 41: Strat over Time Can You change the size of those x & y labels & legend The same for cell 42 End over Time
> > 
> > 
> > @bluejurand sorted!
> 
> I still see them in the same small sizes Zrzut ekranu z 2022-01-05 11-37-28

@bluejurand you are right, I was faster than my saving :), please check now

**Review by bluejurand — APPROVED** [review]

**Review by kglusinski — APPROVED** [review]

**Pull request merged**
