### PR TITLE
adding DBSCAN analysis

### PR DESCRIPTION
**Pull request by AgataJakubowska**

### CODE REVIEW

**Review by bluejurand — COMMENTED** [review]
1. Does `rooms_count` really stores the no. of rooms per every hotel or it is the no. of rooms which bidroom "has" in its inventory? You've made in the beginning assumption that it is option one.
2. Since in this analysis You taken into account only data for two exemplary biggest cities in world, maybe it would be worth to check for some smaller ones wdyt?
3. From `Correlation score heatmap for hotel amenities for ID` it follows that `Business Center` is negatively correlated with `Air Conditioned`?
4. As I see `hotel_type` is label encoded with ordered numbers this can be problematic, because of https://www.analyticsvidhya.com/blog/2020/03/one-hot-encoding-vs-label-encoding-using-scikit-learn/. It probably should be checked how db-scan reacts on ordering, but generally IMO it is safer to do one-hot-encoding?

**Comment by AgataJakubowska** [comment]
> 4\. one-hot-encoding

@bluejurand replying to your suggestions:
1. yes, you are right. I forgot that this value is sth that was shared with us by the hotelier and it is not the value that says the truth about the hotel, so it can make more harm applying that to the analysis , than not to do that. I will remove and reapply the analysis again.
2. I chose the biggest cities just to have cover the biggest variety regarding hotel types. I agree with you that the analysis should be applied also for the smaller ones and I will do that in the next analysis.
3. yes, it is second time - the previous analysis showed the same trend, when according to our data we have such results. One of the explanations that came to my mind is that Business Centers are in such areas - eg. London - that air conditioning is not the feature that is beneficial and always mentioned like hot regions or it is such a standard like free wifi and that is why it is not mentioned. 
4. yes, you are right here - one-ht-encoding s safer here - I will reapply the analysis with correcting that because in current scenario is wrong. The problem with `hotel_type` is not  the ordering but the fact that there are not all numbers: is 1,2,3 etc and later 20 for some reason.

**Comment by bluejurand** [comment]
> > 4. one-hot-encoding
> 
> @bluejurand replying to your suggestions:
> 
> 1. yes, you are right. I forgot that this value is sth that was shared with us by the hotelier and it is not the value that says the truth about the hotel, so it can make more harm applying that to the analysis , than not to do that. I will remove and reapply the analysis again.
> 2. I chose the biggest cities just to have cover the biggest variety regarding hotel types. I agree with you that the analysis should be applied also for the smaller ones and I will do that in the next analysis.
> 3. yes, it is second time - the previous analysis showed the same trend, when according to our data we have such results. One of the explanations that came to my mind is that Business Centers are in such areas - eg. London - that air conditioning is not the feature that is beneficial and always mentioned like hot regions or it is such a standard like free wifi and that is why it is not mentioned.
> 4. yes, you are right here - one-ht-encoding s safer here - I will reapply the analysis with correcting that because in current scenario is wrong. The problem with `hotel_type` is not  the ordering but the fact that there are not all numbers: is 1,2,3 etc and later 20 for some reason.

Quick update regarding point 1.
I had a chance to talk with @ThomasBidroom and he said, that basically in most cases it should be number of rooms in property. The problem is only with old/legacy hotels that could come from scraping and then this number should be verified.

**Comment by AgataJakubowska** [comment]
> 

@bluejurand Ok so lets do this way if you agree: I will reapply analysis correcting the last point for one-hot-encoding for this PR and as a second analysis/ PR  I will reapply this analysis for the same data without the `room_types` (as was agreed with Maurizio a week ago) because I thought you mentioned `room_types` - and I will analyse the resulted clusters for all of them.

**Comment by bluejurand** [comment]
> > 
> 
> @bluejurand Ok so lets do this way if you agree: I will reapply analysis correcting the last point for one-hot-encoding for this PR and as a second analysis/ PR I will reapply this analysis for the same data without the `room_types` (as was agreed with Maurizio a week ago) because I thought you mentioned `room_types` - and I will analyse the resulted clusters for all of them.

SGTM

**Review by bluejurand — APPROVED** [review]
You can display all dataframe columns with 
``` Python
pd.set_option('display.max_columns', None)
pd.set_option('display.expand_frame_repr', False)
```

**Pull request merged**
