### PR TITLE
analysis of the type pf messages named OTA_HotelRateAmountNotifRQ

### PR DESCRIPTION
**Pull request by AgataJakubowska**

### CODE REVIEW

**Comment by bluejurand** [comment]
You are mentioning that `Analysis is done on basis of 8 files that were processed at 1st of December 2021.`, but is see there are 12 files analyzed?

**Review by bluejurand — COMMENTED** [review]
Cell 74: `Start and Rate_Start by HotelCode - comparizon of information sent in these fields`
Plot titles copied from figures above.

**Comment by robsztal** [comment]
Keep in mind that some plot titles are wrong. For example RatePlanCode by HotelCode while on Y axis you have number of hotels. So should be number of hotels by rateplancode. 

Also in my opinion most of these plots shows random information that is not really valuable. I would focus more on couple of plots that shows some trends or have some valuable information.

**Comment by AgataJakubowska** [comment]
> Keep in mind that some plot titles are wrong. For example RatePlanCode by HotelCode while on Y axis you have number of hotels. So should be number of hotels by rateplancode.
> 
> Also in my opinion most of these plots shows random information that is not really valuable. I would focus more on couple of plots that shows some trends or have some valuable information.

@robsztal in my opinion this is the first analysis and is more to get to know what data are showing so every data should be explored even is it not meaningful or as you mention random. Especially in that convention person who was not working on it can see himself the value of the data. Focusing only on couple of plots and showing more meaningful analysis will be in the next steps of analysis for a larger amount of data. 
I took one naming convention across all of the charts, I do not say it is correct one, and the naming was name of shown data  and the split by which is shown

**Comment by AgataJakubowska** [comment]
> Cell 74: `Start and Rate_Start by HotelCode - comparizon of information sent in these fields` Plot titles copied from figures above.

@bluejurand I corrected

**Review by robsztal — APPROVED** [review]

**Comment by AgataJakubowska** [comment]
> You are mentioning that `Analysis is done on basis of 8 files that were processed at 1st of December 2021.`, but is see there are 12 files analyzed?

@bluejurand thank you! corrected!

**Review by bluejurand — APPROVED** [review]

**Pull request merged**
